# Generated by Django 4.2.2 on 2024-11-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_owner_product_status_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['names'], 'permissions': [('can_unpublish_product', 'can unpublish product')], 'verbose_name': 'Имя продукта', 'verbose_name_plural': 'Имена продуктов'},
        ),
    ]
